//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimYonetimAraci
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProcess()
        {
            this.tblUserProcess = new HashSet<tblUserProcess>();
            this.tblWorkFollow = new HashSet<tblWorkFollow>();
        }
    
        public int ProcessID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> CompleteRate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Notes { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> ProcessManagerID { get; set; }
    
        public virtual tblPriorityName tblPriorityName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserProcess> tblUserProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkFollow> tblWorkFollow { get; set; }
        public virtual tblProjects tblProjects { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
