//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimYonetimAraci
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserRoles()
        {
            this.tblUserProcess = new HashSet<tblUserProcess>();
        }
    
        public int UserRolesID { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<int> RoleNameID { get; set; }
    
        public virtual tblRoleNames tblRoleNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserProcess> tblUserProcess { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
