//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimYonetimAraci
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkFollow
    {
        public int WorkFollowID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> WorkFollowDetailsID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CompleteRate { get; set; }
    
        public virtual tblProcess tblProcess { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual tblWorkFollowDetails tblWorkFollowDetails { get; set; }
    }
}
